recaptcha: initial implements
flamego/recaptcha pull request #1
Opened 2021-05-28 08:03 UTC by Altonhe

2021-05-28 20:00 UTC, wuhan005 requested changes

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +	Google VerifyURL = "https://www.google.com/recaptcha/api/siteverify"
```suggestion
	VerifyURLGoogle VerifyURL = "https://www.google.com/recaptcha/api/siteverify"
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +	Global VerifyURL = "https://www.recaptcha.net/recaptcha/api/siteverify"
```suggestion
	VerifyURLGlobal VerifyURL = "https://www.recaptcha.net/recaptcha/api/siteverify"
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +	// Secret key is Required. It's the shared key between your site and reCAPTCHA.
```suggestion
	// Secret key is required. It's the shared key between your site and reCAPTCHA.
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +type Version int
Where is this used?

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +// Options contains options for the recaptcha.RecaptchaV2 middleware.
What about `recaptcha.RecaptchaV3`? It seems that it use the same `Options` as V2.

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +		panic("Null secret input!")
```suggestion
		panic("recaptcha: empty secret")
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +		opts.VerifyURL = Google
```suggestion
		opts.VerifyURL = VerifyURLGoogle
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +		panic("Null secret value input!")
```suggestion
		panic("recaptcha: empty secret")
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +			verifyURL: string(opts.VerifyURL),
```suggestion
			verifyURL: opts.VerifyURL,
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +		opts.VerifyURL = Google
```suggestion
		opts.VerifyURL = VerifyURLGoogle
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +			verifyURL: string(opts.VerifyURL),
```suggestion
			verifyURL: opts.VerifyURL,
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +// request requests specific url and return response.
```suggestion
// request requests specific url and returns response.
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha.go
> +		return nil, errors.Wrapf(err, "request %q: ", url)
```suggestion
		return nil, errors.Wrapf(err, "request %q", url)
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha_test.go
> +		VerifyURL: Global,
```suggestion
		VerifyURL: VerifyURLGlobal,
```

2021-05-28 20:00 UTC, wuhan005 commented on recaptcha_test.go
> +	req, err := http.NewRequest("GET", "/", strings.NewReader("some response"))
```suggestion
	req, err := http.NewRequest(http.MethodGet, "/", nil)
```

2021-05-28 20:00 UTC, wuhan005 commented on v2.go
> +	// Verify user's response and send result back to client.
```suggestion
	// Verify verifies user's response and send result back to client.
```

2021-05-28 20:00 UTC, wuhan005 commented on v2.go
> +		return nil, errors.New("null token")
```suggestion
		return nil, errors.New("empty token")
```

2021-05-28 20:00 UTC, wuhan005 commented on v3.go
> +// RecaptchaV3 is a RecaptchaV3 verify interface.
```suggestion
// RecaptchaV3 is a reCAPTCHA V3 verify interface.
```

2021-05-28 20:00 UTC, wuhan005 commented on v3.go
> +		return nil, errors.New("null token")
```suggestion
		return nil, errors.New("empty token")
```

2021-05-28 20:00 UTC, wuhan005 commented on v2.go
> +	verifyURL string
```suggestion
	// secret is the shared key between your site and reCAPTCHA. [Required]
	secret string
	// response is the user response token provided by the reCAPTCHA client-side integration on your site. [Required]
	response string
	// remoteIP is the user's IP address. [Optional]
	remoteIP string
	// verifyURL is the reCAPTCHA backend service URL.
	verifyURL string
```

2021-05-28 20:00 UTC, wuhan005 commented on v3.go
> +	verifyURL string
```suggestion
	// secret is the shared key between your site and reCAPTCHA. [Required]
	secret string
	// response is the user response token provided by the reCAPTCHA client-side integration on your site. [Required]
	response string
	// remoteIP is the user's IP address. [Optional]
	remoteIP string
	// verifyURL is the reCAPTCHA backend service URL.
	verifyURL string
```

2021-05-29 09:31 UTC, Altonhe commented on recaptcha.go
> +type Version int
Nice catch! It's useless.

2021-05-29 12:17 UTC, Altonhe commented on recaptcha.go
> +			verifyURL: string(opts.VerifyURL),
`opts.VerifyURL` has been defined as type `VerifyURL`, therefore it has to be converted to a string type.

2021-05-29 12:17 UTC, Altonhe commented on recaptcha.go
> +			verifyURL: string(opts.VerifyURL),
same as above

2021-05-29 12:52 UTC, Altonhe commented on recaptcha_test.go
> +	req, err := http.NewRequest("GET", "/", strings.NewReader("some response"))
This test gives an example that the server-side read a response from the user's body and verifies its correctness. Therefore request body must not be `nil`.

2021-06-01 04:53 UTC, wuhan005 approved these changes

2021-06-01 04:53 UTC, wuhan005 commented on recaptcha_test.go
> +	req, err := http.NewRequest(http.MethodGet, "/", strings.NewReader("some response"))
```suggestion
	req, err := http.NewRequest(http.MethodGet, "/", nil)
```

2021-06-01 04:54 UTC, wuhan005 requested changes

2021-06-01 04:54 UTC, wuhan005 commented on v2.go
> +func (r *recaptchaV2) Verify(token string, remoteIP ...string) (*ResponseV2, error) {
docstring here.

2021-06-01 04:54 UTC, wuhan005 commented on v3.go
> +func (r *recaptchaV3) Verify(token string, remoteIP ...string) (*ResponseV3, error) {
docstring here.

2021-06-01 04:55 UTC, Altonhe commented on recaptcha_test.go
> +	req, err := http.NewRequest(http.MethodGet, "/", strings.NewReader("some response"))
This test gives an example that the server-side read a response from the user's body and verifies its correctness. Therefore request body > must not be `nil`.

2021-06-01 04:57 UTC, wuhan005 commented on recaptcha_test.go
> +	req, err := http.NewRequest(http.MethodGet, "/", strings.NewReader("some response"))
But here is a HTTP GET request.

2021-06-01 05:00 UTC, Altonhe commented on recaptcha_test.go
> +	req, err := http.NewRequest(http.MethodGet, "/", strings.NewReader("some response"))
Oops... It should be a post method.

2021-06-01 05:17 UTC, wuhan005 approved these changes

2021-06-12 03:12 UTC, unknwon requested changes

2021-06-12 03:12 UTC, unknwon commented on .github/workflows/lsif.yml
> +    if: github.repository == 'flamego/session'
```suggestion
    if: github.repository == 'flamego/recaptcha'
```

2021-06-12 03:12 UTC, unknwon commented on v3.go
> +type RecaptchaV3 interface {
I think the README also needs an update, because it is currently implying using strcuts not interface:

![CleanShot 2021-06-12 at 11 11 58@2x](https://user-images.githubusercontent.com/2946214/121763481-117ac900-cb6f-11eb-88c6-93f78aad5918.png)

2021-06-12 03:14 UTC, unknwon commented on go.mod
> +	github.com/imroc/req v0.3.0
From the simple usage we have here, I do not think we need a third party package for making simple HTTP requests, please use the stdlib `net/http`.

2021-06-15 16:16 UTC, unknwon requested changes

2021-06-15 16:16 UTC, unknwon commented on recaptcha.go
> +// VerifyURL is the url to verify user input.
```suggestion
// VerifyURL is the API URL to verify user input.
```

2021-06-15 16:16 UTC, unknwon commented on recaptcha.go
> +	// VerifyURLGoogle is the default url to verify reCAPTCHA requests.
```suggestion
	// VerifyURLGoogle is the default API URL to verify reCAPTCHA requests.
```

2021-06-15 16:16 UTC, unknwon commented on recaptcha.go
> +	// VerifyURLGlobal is for the people who can't connect to the Google's server.
```suggestion
	// VerifyURLGlobal is API URL for the people who can't connect to the Google's server.
```

2021-06-15 16:16 UTC, unknwon commented on recaptcha.go
> +	// VerifyURLGlobal is for the people who can't connect to the Google's server.
I have question, what's the reason that we can't always use this one? Thus we can simply remove the `VerifyURLGoogle`.

2021-06-15 16:16 UTC, unknwon commented on recaptcha.go
> +type Version int
Why is this still present?

2021-06-15 16:16 UTC, unknwon commented on recaptcha.go
> +// Options contains options for the recaptcha.RecaptchaV2 and recaptcha.RecaptchaV3 middleware.
```suggestion
// Options contains options for both recaptcha.RecaptchaV2 and recaptcha.RecaptchaV3 middleware.
```

2021-06-15 16:16 UTC, unknwon commented on recaptcha.go
> +	Secret string
```suggestion
	// Secret is the shared key between your site and reCAPTCHA. This field is required.
	Secret string
```

2021-06-15 16:16 UTC, unknwon commented on recaptcha.go
> +		c.Map(client)
```suggestion
		client := &recaptchaV2{
			secret:    opts.Secret,
			verifyURL: string(opts.VerifyURL),
		}
		c.MapTo(client, (*RecaptchaV2)(nil))
```

Same for the V3.

2021-06-28 07:13 UTC, Altonhe commented on recaptcha.go
> +	// VerifyURLGlobal is for the people who can't connect to the Google's server.
The reCAPTCHA API URL under Google's domain can access your cookies regarding Google's service. It makes it easier for Google to recognize you as a human instead of fulfilling nasty captchas and the URL under `recaptcha.net` doesn't have this functionality. Therefore for those who already login to their Google account, use `VerifyURLGoogle` will save their time.

2021-06-28 07:20 UTC, Altonhe commented on recaptcha.go
> +type Version int
deleted

2021-07-31 08:51 UTC, unknwon approved these changes
Approve to unblock.

2021-07-31 08:51 UTC, unknwon commented on recaptcha_test.go
> +	"github.com/stretchr/testify/assert"
```suggestion
	"github.com/stretchr/testify/assert"

	"github.com/flamego/flamego"
```

2021-07-31 08:51 UTC, unknwon commented on recaptcha.go
> +
```suggestion
```

2021-07-31 08:51 UTC, unknwon commented on recaptcha.go
> +	req, err := http.NewRequest(http.MethodGet, url, nil)
Use `http.Get`

2021-07-31 09:08 UTC, unknwon approved these changes

2021-07-31 09:08 UTC, merged

2021-07-31 09:09 UTC, unknwon commented
Please send a PR to the main repository README to add this middleware.